# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvJXgeGSOufBCmF2vW5Id5A7EgIKPqX0
"""



# Chương trình Python để triển khai MergeSort
def mergeSort(dayso):
	global dem
	if len(dayso) > 1:

		# Tìm phần giữa của mảng
		mid = len(dayso)//2

		# Phân chia các phần tử mảng
		L = dayso[:mid]

		# thành 2 nửa
		R = dayso[mid:]

		# Phân loại nửa đầu 
		mergeSort(L)

		# Phân loại nửa sau
		mergeSort(R)

		a = b = c = 0

		# Sao chép dữ liệu vào mảng tạm thời L[] and R[]
		while a < len(L) and b < len(R):
			if L[a] < R[b]:
				dayso[c] = L[a]
				a += 1
				dem += 2
			else:
				dayso[c] = R[b]
				b += 1
				dem += 2
			c += 1
			dem += 1
		dem += 1

		# Kiểm tra xem có phần tử nào còn lại không
		while a < len(L):
			dayso[c] = L[a]
			a += 1
			c += 1
			dem += 3
		dem += 1

		while b < len(R):
			dayso[c] = R[b]
			b += 1
			c += 1
			dem += 3
		dem += 1
	dem += 1 
# In danh sách


def printList(dayso):
	for a in range(len(dayso)):
		print(dayso[a], end=" ")
	print()


# code chính
global dem
dem = 0
dayso = [12, 11, 13, 5, 6, 7]
print("Số cho trước", end="\n")
printList(dayso)
mergeSort(dayso)
print("Số lớn thứ 2 là:", dayso[len(dayso)-2])
print("Số phép tính dùng trong chương trình: ", dem)